### ISSUE TITLE
FatimaFawaz models to be re-exported

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/deepcognition.ai-soda-bottle#1]
@FatimaFawaz I just looked at the python code that you exported from deepcognition.ai and it's not similar to the python code that I usually export. Can you please take a look at [this file](https://github.com/SSOC18/deepcognition.ai-soda-bottle/blob/master/jad-score_52pct/model_v1_vgg_score_0p5.py) and re-export your models for the soda bottle competition in a similar format? Upload them again to the ssoc18.teamshadi.net server so that I commit them into this repository

**Comment by FatimaFawaz** [comment]
Done

**Comment by shadiakiki1986** [comment]
thanks. Committed your models into the repository
